#!/bin/bash

case "$1" in
  start)
    echo "enabled" >> /sys/bus/platform/devices/reg-userspace-consumer.0/state
    hciattach /dev/ttymxc2 texas flow
    ;;
  stop)
    ;;
  *)
    exit 1
esac

exit 0
